services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=migrator-app-record
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
    ui:
        build: "."
        ports:
            - "3000:3000"
        depends_on:
            - db
volumes:
    db:
